# 1. Python Machine Learning basics

## 1) Handling with numpy

In [1]:
import numpy as np

In [4]:
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array shape: ', array1.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array shape:  (3,)


In [5]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array shape: ', array2.shape)

array2 type:  <class 'numpy.ndarray'>
array2 array shape:  (2, 3)


In [6]:
array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array shape: ', array3.shape)

array3 type:  <class 'numpy.ndarray'>
array3 array shape:  (1, 3)


In [7]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [8]:
# data type in ndarray is only possible for same data type

In [9]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [11]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)
#automatically changed into character type
#because their data type should be same

['1' '2' 'test'] <U11


In [12]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [13]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [14]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [15]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [16]:
#easily generating ndarray with arange, zeros, ones

In [18]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [19]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [20]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [21]:
#what if we want to reshape our ndarray size and dimension?
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [22]:
array2 = array1.reshape(2,5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [23]:
array3 = array1.reshape(5,2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [24]:
# if we use index -1 for the reshape(), we can easily reshape into new format

In [27]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
print(array2)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [28]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [29]:
# change 3 dimension ndarray into 2 dimension
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [30]:
# change 1 dimension ndarray into 2 dimension
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)
