# 1. Python Machine Learning basics

## 1) Handling with numpy

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3])
print('array1 type: ', type(array1))
print('array1 array shape: ', array1.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array shape:  (3,)


In [3]:
array2 = np.array([[1,2,3],
                  [2,3,4]])
print('array2 type: ', type(array2))
print('array2 array shape: ', array2.shape)

array2 type:  <class 'numpy.ndarray'>
array2 array shape:  (2, 3)


In [4]:
array3 = np.array([[1,2,3]])
print('array3 type: ', type(array3))
print('array3 array shape: ', array3.shape)

array3 type:  <class 'numpy.ndarray'>
array3 array shape:  (1, 3)


In [5]:
print('array1: {:0}차원, array2: {:1}차원, array3: {:2}차원'.format(array1.ndim,array2.ndim,array3.ndim))

array1: 1차원, array2: 2차원, array3:  2차원


In [6]:
# data type in ndarray is only possible for same data type

In [7]:
list1 = [1,2,3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype)

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int32


In [8]:
list2 = [1,2,'test']
array2 = np.array(list2)
print(array2, array2.dtype)
#automatically changed into character type
#because their data type should be same

['1' '2' 'test'] <U11


In [9]:
list3 = [1,2,3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

[1. 2. 3.] float64


In [10]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

[1. 2. 3.] float64


In [11]:
array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

[1 2 3] int32


In [12]:
array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1 2 3] int32


In [13]:
#easily generating ndarray with arange, zeros, ones

In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int32 (10,)


In [15]:
zero_array = np.zeros((3,2), dtype = 'int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)


In [16]:
one_array = np.ones((3,2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


In [17]:
#what if we want to reshape our ndarray size and dimension?
array1 = np.arange(10)
print('array1:\n', array1)

array1:
 [0 1 2 3 4 5 6 7 8 9]


In [18]:
array2 = array1.reshape(2,5)
print('array2:\n', array2)

array2:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [19]:
array3 = array1.reshape(5,2)
print('array3:\n', array3)

array3:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [20]:
# if we use index -1 for the reshape(), we can easily reshape into new format

In [21]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1,5)
print('array2 shape:', array2.shape)
print(array2)
array3 = array1.reshape(5,-1)
print('array3 shape:', array3.shape)
print(array3)

[0 1 2 3 4 5 6 7 8 9]
array2 shape: (2, 5)
[[0 1 2 3 4]
 [5 6 7 8 9]]
array3 shape: (5, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [22]:
array1 = np.arange(8)
array3d = array1.reshape((2,2,2))
print('array3d:\n', array3d.tolist())

array3d:
 [[[0, 1], [2, 3]], [[4, 5], [6, 7]]]


In [23]:
# change 3 dimension ndarray into 2 dimension
array5 = array3d.reshape(-1,1)
print('array5:\n', array5.tolist())
print('array5 shape:', array5.shape)

array5:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape: (8, 1)


In [24]:
# change 1 dimension ndarray into 2 dimension
array6 = array1.reshape(-1,1)
print('array6:\n', array6.tolist())
print('array6 shape:', array6.shape)

array6:
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape: (8, 1)


## 2) Indexing ndarray dataset

In [25]:
# what if we want to cut off some part of the dataset? -> use indexing

In [26]:
# selecting single data value
array1 = np.arange(start=1, stop=10)
print('array1:', array1)

# we should always remember that indexing starts from "0"
value = array1[2]
print('value:', value)
print(type(value))

array1: [1 2 3 4 5 6 7 8 9]
value: 3
<class 'numpy.int32'>


In [27]:
print('last value:', array1[-1], 'second last value:', array1[-2])

last value: 9 second last value: 8


In [28]:
# we can also easily edit the ndarray vlue with indexing
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [30]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print(array2d) #reshape into 2 dimension

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print('(row=0, col=0) indexing value:', array2d[0,0])
print('(row=0, col=1) indexing value:', array2d[0,1])
print('(row=1, col=0) indexing value:', array2d[1,0])
print('(row=2, col=2) indexing value:', array2d[2,2])

(row=0, col=0) indexing value: 1
(row=0, col=1) indexing value: 2
(row=1, col=0) indexing value: 4
(row=2, col=2) indexing value: 9


In [33]:
# if we use : sign, we can slice and use sequential data value
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


In [36]:
# empty before : means start from the beginning
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

# empty after : means ends at the last value
array5 = array1[3:]
print(array5)

# empty numbers with : means include all values
array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [37]:
# then, how can we slice the data values from 2 dimension?

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3,3)
print('array2d:\n',array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2d:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


In [38]:
# if we empty the number at the 2 dimension ndarray, it returns 1 dimension
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 
      'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


In [39]:
# Fancy Indexing
# set index set with list or ndarray, then return ndarray in that position

array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0,1], 2]
print('array2d[[0,1],2] => ', array3.tolist())

array4 = array2d[[0,1], 0:2]
print('array2d[[0,1], 0:2] => ', array4.tolist())

array5 = array2d[[0,1]]
print('array2d[[0,1]] => ', array5.tolist() )

array2d[[0,1],2] =>  [3, 6]
array2d[[0,1], 0:2] =>  [[1, 2], [4, 5]]
array2d[[0,1]] =>  [[1, 2, 3], [4, 5, 6]]


In [40]:
# Boolean indexing
# possible to condition filtering and searching
array1d = np.arange(start=1, stop=10)
array3 = array1d[array1d > 5] #set Boolean indexing in []
print('array1d > 5 Boolean indexing result: ', array3)

array1d > 5 Boolean indexing result:  [6 7 8 9]


In [42]:
# what if just simply do condition filtering?
array1d > 5 # it returns true or false

array([False, False, False, False, False,  True,  True,  True,  True])

In [43]:
boolean_indexes = np.array([False, False, False, False, False,
                           True, True, True, True])
array3 = array1d[boolean_indexes]
print('Boolean index filtering result:', array3)

Boolean index filtering result: [6 7 8 9]


In [44]:
indexes = np.array([5,6,7,8])
array4 = array1d[indexes]
print('filtering with normal indexing:', array4)

filtering with normal indexing: [6 7 8 9]


## 3) sort() and argsort()

In [52]:
org_array = np.array([3,1,9,5])
print('original matrix:', org_array)

# use np.sort()
sort_array1 = np.sort(org_array)
print('np.sort() result matrix: ', sort_array1)
print('original matrix after np.sort(): ', org_array)

original matrix: [3 1 9 5]
np.sort() result matrix:  [1 3 5 9]
original matrix after np.sort():  [3 1 9 5]


In [53]:
#sorting with ndarray.sort()
sort_array2 = org_array.sort()
print('org_array.sort() result matrix: ', sort_array2)
print('original matrix after org_array.sort(): ', org_array)

org_array.sort() result matrix:  None
original matrix after org_array.sort():  [1 3 5 9]
